server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: '@name@'
    version: '@version@'
  main:
    banner-mode: "OFF"
  liquibase:
    change-log: classpath:db/liquibase-changelog.xml
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:cat}?useUnicode=true&characterEncoding=utf8
    username: ${DB_USER:cat}
    password: ${DB_PASSWORD:cat}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: false
    hibernate:
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
      ddl-auto: validate #let liquibase to manage our database, hibernate should only validate it
    properties:
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.temp.use_jdbc_metadata_defaults: false

logging:
  level:
    org.springframework: INFO
    io.lombocska: DEBUG

