server:
  port: ${SERVER_PORT:8761}
spring:
  application:
    name: '@name@'
    version: '@version@'
  main:
    banner-mode: "OFF"
eureka:
  client:
    register-with-eureka: false
    fetchRegistry: false
    server:
      wait-time-in-ms-when-sync-empty: 0



